version: '3'

services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: monitor-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
    restart: unless-stopped
    user: '472'
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - monitor-network
    labels:
      org.label-schema.group: "monitoring"
  
  prometheus:
    image: prom/prometheus:v${PROM_VERSION}
    container_name: monitor-prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - 9090
    networks:
      - monitor-network
    labels:
      org.label-schema.group: "monitoring"

networks:
  monitor-network:
    driver: bridge

volumes:
    prometheus_data: {}
    grafana_data: {}

